### ISSUE TITLE
Lỗi phím tắt

### ISSUE THREAD

**Issue by ManhHoDinh** [caodoanh2001/UIT-OpenViIC-labeller#1]
Lệnh ctrl tab máy em không hoạt động

**Comment by caodoanh2001** [comment]
Em gõ Tab thôi thử nhé, không cần Ctrl+Tab thử xem sao em

**Comment by ManhHoDinh** [comment]
> Lệnh ctrl tab máy em không hoạt động

dạ được rồi anh

**Comment by caodoanh2001** [comment]
ok cảm ơn em.
