### ISSUE TITLE
Không hiện cửa sổ tiếp theo

### ISSUE THREAD

**Issue by lebichloan** [caodoanh2001/UIT-OpenViIC-labeller#3]
Khi bấm vào tiếp theo không hiện cửa sổ để gán nhãn

**Comment by caodoanh2001** [comment]
em dùng HĐH nào thế em
nếu là window thì e dùng 32bit hay 64bit

**Comment by lebichloan** [comment]
Dạ em dùng win10 64bit ạ

Vào 14:56, T.3, 24 Th5, 2022 Doanh B C ***@***.***> đã viết:

**Comment by caodoanh2001** [comment]
em cho anh mssv đi em
rồi em nhắn id + pass teamview qua google chat, anh vàomáy em xem thử

**Comment by lebichloan** [comment]
MSSV của em là 21521083 ạ. Còn id + pass teamview là gì vậy ạ ?

**Comment by caodoanh2001** [comment]
Lỗi này là do em để tool và thư mục ảnh ở folder đồng bộ hóa (OneDrive, Google Drive, ...) nên tool sẽ không load ảnh được.

Fix: em để ở local (ổ đĩa của máy) thì sẽ load được.
