### ISSUE TITLE
21521538

### ISSUE THREAD

**Issue by TinSpaghettiCode** [caodoanh2001/UIT-OpenViIC-labeller#4]
Không dùng được Ctrl ->, Ctrl <- và Ctrl Tab

**Comment by caodoanh2001** [comment]
Em ko dùng được Ctrl -> có thể là con trỏ nháy đang ở trong text box. em thử bấm Tab ra ngoài rồi thử Ctrl -> lại nhé em

**Comment by caodoanh2001** [comment]
À, có vẻ em chỉ cần dùng TAB để out ra khỏi text box thôi. ko cần CTRL + TAB
