### ISSUE TITLE
Lỗi không nhảy lên ảnh tiếp theo sau khi gặp những tấm ảnh trùng - 21521538

### ISSUE THREAD

**Issue by TinSpaghettiCode** [caodoanh2001/UIT-OpenViIC-labeller#6]
Dạ e có một vấn đề là khi e làm tới khoảng 800 ảnh thì gặp gần 100 bức ảnh trùng và có cả comment trước đó, sau khi skip tới ảnh thứ 900 và ghi comment cho một vài ảnh mới, đã lưu và backup thành công nhưng khi bật lên lại nó vẫn ở mãi ở số 800 ạ

**Comment by caodoanh2001** [comment]
Em lấy file json đã gán xong 900 ảnh, sau đó load lại xem được ko em

**Comment by TinSpaghettiCode** [comment]
Dạ e có thử load lại, save as ra chỗ khác thì vẫn k được. A xem giúp e trên hệ thống file của 21521538 backup lên nó ghi là được bao nhiêu ảnh rồi z ạ

**Comment by caodoanh2001** [comment]
ok em để anh kiểm tra lại

**Comment by caodoanh2001** [comment]
hiện tại hệ thống ghi nhận em đã gán 820 ảnh. có gì em check tin nhắn bên gmail, anh dùng anydesk vào máy xem xem tình hình

**Comment by caodoanh2001** [comment]
Hiện tại lỗi này là do tập ảnh load lần đầu khác với tập ảnh load lần sau. mà file annotation lại là của lần đầu, do đó gây ra lỗi.
